apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vscode-runme
  namespace: stateful
  description: Runme vscode Extension
  annotations:
    github.com/project-slug: runmedev/vscode-runme
spec:
  type: service
  owner: user:stateful/sourishkrout
  lifecycle: production
  providesApis:
    - component:stateful/runme
  dependsOn:
    - component:stateful/firefly
