// @generated by protoc-gen-es v1.8.0 with parameter "target=ts,import_extension=none"
// @generated from file foyle/v1alpha1/trainer.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Block, Doc } from "./doc_pb";

/**
 * Example represents an example to be used in few shot learning
 *
 * @generated from message Example
 */
export class Example extends Message<Example> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: repeated float embedding = 2;
   */
  embedding: number[] = [];

  /**
   * @generated from field: Doc query = 3;
   */
  query?: Doc;

  /**
   * @generated from field: repeated Block answer = 4;
   */
  answer: Block[] = [];

  constructor(data?: PartialMessage<Example>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "Example";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "embedding", kind: "scalar", T: 2 /* ScalarType.FLOAT */, repeated: true },
    { no: 3, name: "query", kind: "message", T: Doc },
    { no: 4, name: "answer", kind: "message", T: Block, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Example {
    return new Example().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Example {
    return new Example().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Example {
    return new Example().fromJsonString(jsonString, options);
  }

  static equals(a: Example | PlainMessage<Example> | undefined, b: Example | PlainMessage<Example> | undefined): boolean {
    return proto3.util.equals(Example, a, b);
  }
}

/**
 * @generated from message RAGResult
 */
export class RAGResult extends Message<RAGResult> {
  /**
   * @generated from field: Example example = 1;
   */
  example?: Example;

  /**
   * @generated from field: double score = 2;
   */
  score = 0;

  constructor(data?: PartialMessage<RAGResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "RAGResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "example", kind: "message", T: Example },
    { no: 2, name: "score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RAGResult {
    return new RAGResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RAGResult {
    return new RAGResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RAGResult {
    return new RAGResult().fromJsonString(jsonString, options);
  }

  static equals(a: RAGResult | PlainMessage<RAGResult> | undefined, b: RAGResult | PlainMessage<RAGResult> | undefined): boolean {
    return proto3.util.equals(RAGResult, a, b);
  }
}

